#!/bin/bash
#
# (ↄ)2012 vanScheijen
#---------------------
# Output swap usage from processes that are currently swapping.
# Tip: Use `lsswap|sort -nk6` to sort by most usage.
#

swap_total=0

for piddir in $(find /proc/ -maxdepth 1 -type d -name '[0-9]*'); do
	swap_pid=0
	pid=`echo $piddir | cut -d / -f 3`
	program_name=`ps -p $pid -o comm --no-headers`
	for swap in $(grep Swap $piddir/{status,smaps} 2>/dev/null | awk '{print $2}'); do
		(( swap_pid += swap ))
	done
	if [[ $swap_pid -gt 0 ]]; then
		echo -e "$program_name (pid=${pid}) - Swap usage: $swap_pid"
		(( swap_total += swap_pid ))
	fi
done

printf "%.s=" $(seq 1 $(tput cols))
echo "Total swap usage: $swap_total"

